apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-with-rbd-pvc
  name: nginx-with-rbd-pvc
spec:
  containers:
  - image: nginx:alpine
    name: nginx
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: rbd-pvc